# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: 🚀 Feature Request
description: Suggest a Product Detector idea
# title: " "
labels: [enhancement]

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
      
